# Generated by Django 4.1.2 on 2023-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metrouser",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=20, null=True)),
                ("mno", models.BigIntegerField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={"db_table": "metrouser", "managed": False,},
        ),
        migrations.DeleteModel(name="User",),
    ]
