# Generated by Django 4.1.4 on 2023-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_metrouser_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='eedback',
        ),
    ]
