# Generated by Django 4.1.4 on 2023-01-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
