# Generated by Django 4.1.4 on 2023-01-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_alter_feedback_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.CharField(blank=True, max_length=5000, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'help',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Traindetails',
        ),
    ]
